### ISSUE TITLE
Error: 'pop from an empty set'

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#13]
In:
https://wepp1.nkn.uidaho.edu/weppcloud/runs/fdbd29b9-75bd-4de0-bb80-d9c55ab00324/lt/
https://wepp1.nkn.uidaho.edu/weppcloud/runs/885b4b1f-a0e3-4d05-8ecd-3017a3cdb932/lt/
https://wepp1.nkn.uidaho.edu/weppcloud/runs/cca8d0d4-83ad-4423-9b58-b8cf94a882a3/lt/
https://wepp1.nkn.uidaho.edu/weppcloud/runs/3b146b51-3f39-46f9-988a-ff033d19d730/lt/

Error running wepp:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wepppy/weppcloud/app.py", line 1524, in submit_task_run_wepp
    wepp.prep_watershed()
  File "/usr/lib/python3/dist-packages/wepppy/nodb/wepp.py", line 365, in prep_watershed
    self._prep_channel_soils(translator)
  File "/usr/lib/python3/dist-packages/wepppy/nodb/wepp.py", line 467, in _prep_channel_soils
    version = versions.pop()
KeyError: 'pop from an empty set'

**Comment by rogerlew** [comment]
Looks like the soils nodb is lost the soils for the channels.

I rebuilt cca8d0d4-83ad-4423-9b58-b8cf94a882a3 and it ran. Any idea why it when it might have lost the channels?

https://wepp1.nkn.uidaho.edu/weppcloud/runs/28d7cdec-3c8c-4265-9237-71dff2d34073/lt/

**Comment by rogerlew** [comment]
Looks like it was falling back to statsgo in those runs. The statsgo build wasn't building soils for the channels. Should work now?
