### ISSUE TITLE
Runs folder not displaying

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#134]
The runs folder doesn't display.

**Comment by rogerlew** [comment]
I can see the wepp/runs folders. Which project?

**Comment by marianadobre** [comment]
Sorry, I wasn't too specific. 
When I am in my account and I click on My Runs, I get the Internal Server Error

**Comment by rogerlew** [comment]
Awe, This should work now, though it might take a while to load.

**Comment by ames-fowler** [comment]
I am receiving the same error. 
My Runs -> Internal Server Error 
Apache/2.4.18 (Ubuntu) Server at wepp1.nkn.uidaho.edu Port 443
