### ISSUE TITLE
Area off in Combined Watershed Viewer - watershed summary display 

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#160]
The area in the watershed summary is off, probably taken from a different cell. In the attached image, the area shows as 2.7 ha, but I think it should be 120 ha. 

![image](https://user-images.githubusercontent.com/37674030/70840767-7feb9900-1dc9-11ea-97f3-018f3c81d405.png)

**Comment by rogerlew** [comment]
That area is for actually for the hillslope, not for the watershed.

**Comment by marianadobre** [comment]
Right! Sorry about that!

M
