### ISSUE TITLE
Flowpath phosphorus gridded output

### ISSUE THREAD

**Issue by rogerlew** [rogerlew/wepppy#24]
@marianadobre 
loss is based on the plot files. Not sure where the phosphorus data should come from to generated the P maps.

**Comment by rogerlew** [comment]
https://wepp1.nkn.uidaho.edu/weppcloud/runs/9ac78250-bb06-4978-bd6a-0f9bd8254fc3/lt/

![image](https://user-images.githubusercontent.com/3652906/37893718-c37092a2-3090-11e8-80f8-d37e361be45c.png)

**Comment by marianadobre** [comment]
I'll ask Anurag if he can add P columns in the plot files for generate Phosphorus plot files.

**Comment by marianadobre** [comment]
I don’t think we need gridded vizualtizations for the runoff/lateral flow/baseflow. Nobody will care about it. For management purposes, people will care about sediments and particulate phosphorus. We don’t have the Particulate P in the plot files and Anurag said that might be a hassle to add. So can we just create the variable by multiplying sediments by that P sediment concentration coefficient? We will get the same thing. 
So at most, these are the legends we can display. (some we already have). We don’t have to plot everything but we could have them:
Hillslopes Visualizations (average annuals loss_pw0.txt)
•	Surface Runoff
•	Subsurface Lateral Flow
•	Baseflow
•	Sediment Yield
•	Sediment Deposition/Loss
•	Solub. React. P
•	Particulate P
•	Total P
Channels Visualizations (average annuals loss_pw0.txt)
•	Discharge
•	Subsurface Lateral Flow
•	Baseflow
•	Sediment Yield
•	Sediment Deposition/Loss
•	Solub. React. P
•	Particulate P
•	Total P
Gridded Visualizations (plot_*.txt)
•	Sediment Yield
•	Sediment Deposition/Loss
•	Particulate P (multiply sediment yield by coefficient)

**Comment by rogerlew** [comment]
Is Sediment Yield just the positive Sediment Deposition/Loss values?
Jim had gridded output for phosphorus. Was that calculated from the sediment yield?

**Comment by marianadobre** [comment]
Sediment yield is how much soil detached from the hillslope. Sediment
deposition, is how much of that detached soil deposited at the bottom of
the hillslope or in areas down the hill that have gentler slopes. Sediment
yield is how much sediment leaves the hillslope.

I don't know what Jim did. I can ask him and see what he says.

M

**Comment by rogerlew** [comment]
Thanks for the explanation.

In the hillslope summary table sediment yield + sediment deposition = sediment loss so the "Deposition/Loss" on the hillslope output is calculated as yield - deposition.

The plot files only have deposition/loss as a single column with positive values. So, the only way we have to calculated gridded sediment yield would be to take the positive dep/loss values. Particulate P would just be a linear transformation of that, which might not be that interesting.

On wepp2 lt there are "weppTotalPLoaa.asc" files, Jim has the source on wepp2. At this point, I'm pretty sure the gridded output has P values by hillslope, and not by flowpath.

**Comment by marianadobre** [comment]
Yes, I don't remember Jim talking about gridded output for P. I think we
should plot whatever we can now and think about adding other features
later.
