### ISSUE TITLE
Manning's N default value

### ISSUE THREAD

**Issue by rogerlew** [rogerlew/wepppy#272]
![image](https://github.com/rogerlew/wepppy/assets/3652906/3d214731-af30-4c50-813e-e1ae9436420c)

Current defaults are 0.3 for total and 0.04 for bare
![image](https://github.com/rogerlew/wepppy/assets/3652906/d5af8878-5006-46b1-83fa-63aef729e68b)
![image](https://github.com/rogerlew/wepppy/assets/3652906/07e7a3ec-85e6-4530-950d-792a2c9cdf3b)

**Comment by rogerlew** [comment]
With 0.04 total and 0.03 for bare

![image](https://github.com/rogerlew/wepppy/assets/3652906/a185e3df-7ccd-4a5a-9735-ea95969cb8d7)
![image](https://github.com/rogerlew/wepppy/assets/3652906/51187601-465b-48a0-a649-82768770ee91)

**Comment by rogerlew** [comment]
peak flows original
![image](https://github.com/rogerlew/wepppy/assets/3652906/b30796e5-25b2-4b5b-add9-a169d07eaef2)


revised
![image](https://github.com/rogerlew/wepppy/assets/3652906/fe164196-ba34-4bbc-a88c-71aedabf07a8)

**Comment by rogerlew** [comment]
![image](https://github.com/rogerlew/wepppy/assets/3652906/77c5b639-5023-4f04-98b1-dd6738651049)
![image](https://github.com/rogerlew/wepppy/assets/3652906/1f00aafd-ff2c-44f7-ba9c-d7665bb1dfff)

**Comment by bssheppard** [comment]
Interface looks good! It is great to have a parameter input. I think the actual process being modeled in WEPP has an issue:

![burned_unburned](https://github.com/rogerlew/wepppy/assets/167808455/7a6ee119-a97a-4474-9966-4791c4e6d106)

Why do the hydrographs start with so much flow? Seeing the difference in the burned and unburned makes me think it is how the water is routed, and not an initial condition.

It does not seem right that burned and unburned have the same time to peak, and the less 'flashy' shape of the burned hydrograph is suspicious.

**Comment by bssheppard** [comment]
![image](https://github.com/rogerlew/wepppy/assets/167808455/0764b746-1d29-4744-914e-6783f073bb4e)

Here are 2 burned single storm runs with a more reasonable rainfall than the example above. Neither Manning n case produced runoff in unburned conditions. (reasonable)

the timing and shape and increase in peak flow look correct!

I looked at the event rainfall, and it does not appear to be distributing the precipitation in time:
![image](https://github.com/rogerlew/wepppy/assets/167808455/a2a75244-2e4a-4de4-9aae-7655d7fad9ca)

the 31 mm at time =0 could be why the hydrograph is starting above zero
I will do a fresh run to see if I get the same results, if so, I can add something else to the to do list.

**Comment by rogerlew** [comment]
Parameterization experiment from Garrett

![image](https://github.com/rogerlew/wepppy/assets/3652906/b1c9d653-cb12-49e2-a2c2-6cd025dbd0e1)
