### ISSUE TITLE
Problem with building the soils

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#30]
I got the following error when I selected single management for the entire watershed (high severity fire). I went back and changed the management for each hilllsope and then the soils built ok. 

![image](https://user-images.githubusercontent.com/37674030/37935269-bd5a90d2-3105-11e8-9c15-fcf69cb90035.png)

**Comment by rogerlew** [comment]
I guess single landuse was never fully implemented. Now it is.
