### ISSUE TITLE
GHCN climates

### ISSUE THREAD

**Issue by rogerlew** [rogerlew/wepppy#309]
Hi Roger - would it be possible to make WEPP climate files from GHCNd daily precipitation and temperature values https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/ These are the stations that is used to make CLIGEN PAR files and are at lower elevations. 
 
I was thinking to compare this product with daymet, gridmet, prism, and dep-nexrad and to come up with correction factor for DEP-nexrad precip and temps. Previously, we did this at SNOTEL site but for this we can do the same at GHCNd locations.
 
ULMO python (https://ulmo.readthedocs.io/en/latest/api.html#module-ulmo.ncdc.ghcn_daily) under "NCDC Global Historical Climate Network (GHCN) Daily" has a way to download daily values of precipitation and temperature that we could use directly or we could download these directly from website.

**Comment by akrherz** [comment]
> dep-nexrad and to come up with correction factor for DEP-nexrad precip and temps.

One item I would caution in this space is that GHCN is generally 24 hour data observed at 7 AM, whereas at least DEP-nexrad is something close to US Central Midnight.  There is a systematic bias between the two datasets given how a cold low at 7 AM can occupy two days.  Here's a simple bias computation for the Des Moines ASOS by comparing the 6 Z *cough midnight* daily high and low vs a 24 hour computed at different times of the day:

![high](https://github.com/user-attachments/assets/c72720dd-1cec-45fb-b631-8f59204dcedf)

Thankfully there is very little present day GHCN data taken in the afternoon, but some still exists and it was much more common a number of decades ago.

**Comment by rogerlew** [comment]
implemented in commit https://github.com/rogerlew/wepppy/commit/403d4a7862d9cd86e7bd57441846a1b577bda076
