### ISSUE TITLE
Plot lateral flow and baseflow for hillslopes

### ISSUE THREAD

**Issue by rogerlew** [rogerlew/wepppy#31]
@marianadobre 

lateral flow is the same as subrunoff?
which colormap should we use? same as runoff?

baseflow is m^3 in summary table. should it be plotted in mm?
What colormap should be used?

**Comment by rogerlew** [comment]
Is it important to be able to compare the relative runoff vs lateral vs baseflow for each hillslope? might make more sense to give people a stacked bar chart?

**Comment by marianadobre** [comment]
I guess they mean subsurface runoff, which is subsurface lateral flow. So I would say they are the same. But they are different from runoff. 

Yes, we should plot basedlow in mm.

As for legend colors, we can make them the same as for runoff.

Mariana

**Comment by marianadobre** [comment]
Oh, yes, that would be great, if possible.

This is an example of a similar graph we have in a publication:

**Comment by rogerlew** [comment]
Sorry, I don't see the graph

**Comment by rogerlew** [comment]
![5383_1522167049329](https://user-images.githubusercontent.com/3652906/37980085-16a26068-319f-11e8-85c1-57017f362840.jpeg)

**Comment by rogerlew** [comment]
implemented as interactive d3 chart.

**Comment by marianadobre** [comment]
I really like the graph although for the one run I looked at I could not
see lateral and baseflow. Will do a few more runs today, though.

Also, can we change the name to Hillslope Daily Runoff/.... since these
results are from hillslopes only? Oh, and can we also plot precipitations
at the top of the graph? If possible--it already looks great!

**Comment by rogerlew** [comment]
The lateral and baseflow is probably always 0 or close to 0. It is using data from chnwb.txt right now for that. I like the idea of having precip from the top.

**Comment by marianadobre** [comment]
The should not me close to 0 all the time, unless it's a small watershed
(like the one I ran) or using generic climate (like the one I used). So I
will try a larger watershed with PRISM now.
