### ISSUE TITLE
Legend for gridded viz

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#33]
In gridded visualizations, soil deposition/loss is not cropped. Can we crop it just to have it look like the other maps?

And there might be something off with the legend for the gridded visualizations (see below). I can’t tell if a pixel is 1 kg/ha or 39901 kg/ha. maybe it's correct but at first glance it seems off to me. 

![image](https://user-images.githubusercontent.com/37674030/37983013-fffc975e-31a6-11e8-8b81-3c73da0b056b.png)

![image](https://user-images.githubusercontent.com/37674030/37983024-0535f7e2-31a7-11e8-8c7d-8686b7fcc06b.png)

**Comment by rogerlew** [comment]
The red just means that the cell is that value or higher. So if you had a tolerance of 2000 kg/ha you could move the slider so the max is at 2000.0. Then anything in red would indicate a cell that is above that value.

It would be nice to crop to the watershed bounds. Looks like the leaflet-geotiff module doesn't support transparency. It supposedly supports a clip specified as lat, long coords. But it doesn't seem to be working.

**Comment by marianadobre** [comment]
I see. Can we display > or < together with the smallest/largest values?

**Comment by rogerlew** [comment]
Yeah, I that might help.

Might have figured out how to get the gridded output to only display inside the watershed. It builds the grid when wepp runs. So any existing projects won't be clipped.

**Comment by rogerlew** [comment]
Turns out it is more difficult than one might think to add the > and < symbols because of how the unitization is implemented. I'm going to close this and tag as won't fix. We can address it later if it comes up as a common problem for users.

**Comment by marianadobre** [comment]
Sounds good.
