### ISSUE TITLE
Radio button for wepp_ui.txt

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#48]
wepp_ui is an empty text file. If present in the runs folder, WEPP will run hourly seepage. Otherwise it will run daily seepage. Sometimes results look better with it, sometimes they don't. So the selectable radio button would be great.

**Comment by rogerlew** [comment]
This will get pushed to wepp1 later today. It is off by default and is only visible for power users (when logged in).

**Comment by marianadobre** [comment]
Great! Thanks! What's the command to run it on VM?

**Comment by rogerlew** [comment]
It has a method in wepppy.nodb.wepp

```
wepp = Wepp.getInstance(wd)
wepp.set_hourly_seepage(True)
```

**Comment by marianadobre** [comment]
Thanks. I will run Blackwood now with many csa/mcl and hourly seepage to
see how it looks.
