### ISSUE TITLE
Error while running Fernan watershed (with general interface)

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#54]
Got the following error while running Lake Fernan:

In:
https://wepp1.nkn.uidaho.edu/weppcloud/runs/c15a638c-1c38-4426-8593-b25e1d9e8c80/0/

Error running wepp

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wepppy/weppcloud/app.py", line 1755, in submit_task_run_wepp
    wepp.run_hillslopes()
  File "/usr/lib/python3/dist-packages/wepppy/nodb/wepp.py", line 486, in run_hillslopes
    assert run_hillslope(wepp_id, runs_dir)
  File "/usr/lib/python3/dist-packages/wepppy/wepp/runner/wepp_runner.py", line 105, in run_hillslope
    % (wepp_id, log_fn))
Exception: Error running wepp for wepp_id 87
See /geodata/weppcloud_runs/c15a638c-1c38-4426-8593-b25e1d9e8c80/wepp/runs/p87.err

**Comment by rogerlew** [comment]
Looks like there was an error with the management file parser. It wasn't correctly parsing all of the crops for years with multiple crops. I'm doing a test run on my vm. Will update wepp1 shortly.

**Comment by rogerlew** [comment]
I will add a route so it is easier to figure out how the wepp and topaz ids coorespond: e.g.
http://127.0.0.1:5000/runs/c15a638c-1c38-4426-8593-b25e1d9e8c80/query/topaz_wepp_map/

**Comment by rogerlew** [comment]
I rebuilt the managements on the wepp1 project and started wepp.

You can check the status by refreshing:
https://wepp1.nkn.uidaho.edu/weppcloud/runs/c15a638c-1c38-4426-8593-b25e1d9e8c80/report/wepp/log/
