### ISSUE TITLE
Change min soil depth to 200 mm

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#56]
I have just encountered a soil with a depth of 130 mm in Tahoe, which caused the model to stop. As it turns out, the current version of WEPP that we have on the interface gets stuck on hillslopes where the overall soil depth is <200 mm. So we need to change the SSURGO soils such that if the soil depth is < 200 mm, we change it to 200.

**Comment by marianadobre** [comment]
Yes. It's 1652031.

**Comment by rogerlew** [comment]
fix is up on github, not wepp1

**Comment by marianadobre** [comment]
Tried **git lfs fetch --all** and it says it found 16 objects and fetching them. But it doesn't say if it also succeeded at fetching them. I don't think is updating anything since that soil is still downloaded with 50 and 130 mm soil depths. Should I try again with pull?

**Comment by marianadobre** [comment]
It looks like the depth in the last layer in the soil file needs to be 200. 

What we had:
```
50 (-->depth of first soil layer is 50 mm)
130 (-->depth of second soil layer = 130-50 = 80)
total soil depth = 50 + 80 = 130 mm
```
What we have now:
```
50 (-->depth of first soil layer is 50 mm)
160 (-->depth of second soil layer = 160-50 = 110)
total soil depth = 50 + 110 = 160 mm
```
How it needs to be:
```
50 (-->depth of first soil layer is 50 mm)
2000 (-->depth of second soil layer = 100-50 = 150)
total soil depth = 50 + 150 = 200 mm
```

**Comment by rogerlew** [comment]
I just pushed a commit. Let's go with a minimum of 210 mm so it is consistent with the minimum for Urban and water.

```

Any comments:
1 1
'Lithnip-Meiss-Hawkinspeak association, 30 to 75 percent slopes'		'GRX-SL'	2	0.2300	0.7500	4764260.00	0.0076	2.9652	0.0000
	   50.000	    1.30	 100.8000	 10.0	   0.3294	   0.1647	  66.80	  14.00	   1.50	  12.50	  83.00
	  210.000	    1.30	 100.8000	 10.0	   0.2947	   0.1439	  65.90	  15.00	   0.75	  12.50	  71.50
1 10000.0 0.00018
```

**Comment by marianadobre** [comment]
Thanks! I think I was able to get the changes with git fetch all. Running
it now and will see if they work.

**Comment by rogerlew** [comment]
Cool, glad git is cooperating.

The one with 160.0 on the last line actually ran for me.

**Comment by marianadobre** [comment]
Huh, interesting.
