### ISSUE TITLE
Remove first two years from sediments wen calculating stats

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#57]
WEPP will tend to erode the channels more in the first two years. For the users, we need to print Average annual sediments starting with year 3.

**Comment by rogerlew** [comment]
I think we should change the default number of years from 1 to something >= 3. I was thinking 5?

**Comment by marianadobre** [comment]
I like that idea, yes. 5 should be good.

**Comment by rogerlew** [comment]
This has been implemented. By default it excludes the first two years. Additional years can be excluded using the `exclude_yr_indxs` get parameter.
e.g.
https://wepp1.nkn.uidaho.edu/weppcloud/runs/bd62939a-0658-4e3d-b0d4-d8d4cd5991a1/report/wepp/summary/?exclude_yr_indxs=0

![image](https://user-images.githubusercontent.com/3652906/38340923-d5e927e0-382a-11e8-850b-aebe67239732.png)
