### ISSUE TITLE
Error in climates

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#59]
I closed the window by mistake but you can still see the project's name. Not sure why it crashed. 

![image](https://user-images.githubusercontent.com/37674030/38377881-f450d7ec-38b0-11e8-9826-4311839f9656.png)

**Comment by rogerlew** [comment]
Looks like the climate wasn't built. Might have forgot to hit the build button.
![image](https://user-images.githubusercontent.com/3652906/38378574-0690a05c-38b3-11e8-8b6f-929136f057b5.png)

The interface could probably provide better feedback error handling feedback there.

**Comment by marianadobre** [comment]
Gosh! I was convinced I did that  few times. Apparently not.
