### ISSUE TITLE
exclude_yr_index error on VM

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#60]
I get this error when running it on the virtual machine. Do I need another line of code for this?

![image](https://user-images.githubusercontent.com/37674030/38429192-9103fdd2-3972-11e8-8515-c08ea7f5511f.png)

**Comment by rogerlew** [comment]
the `exclude_yr_indx` arg specifies which years should be excluded. Added a fix so it passes `[0, 1]` by default to exclude the first 2 years.

**Comment by marianadobre** [comment]
Sorry, another one. :)

![image](https://user-images.githubusercontent.com/37674030/38434334-cf7afb5a-3982-11e8-9c81-5d6556287600.png)

**Comment by marianadobre** [comment]
One more. :)

![image](https://user-images.githubusercontent.com/37674030/38443694-731cf3ee-39a1-11e8-9631-ed529f361422.png)

**Comment by rogerlew** [comment]
That lives in
‘’’
from wepppy.wepp.out import TotalWatSed
‘’’
