### ISSUE TITLE
Observed Data Model Fit

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#62]
In the box for Observed data model fit, do we add the dates, too? Or we just assume the user will add their data starting with 01/01/yyyy of the first year in the climate file to 12/31/yyyy of the last year in the climate file? If so, what do we do with missing data? And does the user also ads the first two years or not?

**Comment by rogerlew** [comment]
That needs documented better on the interface.

Here is an example. It doesn't actually need the Water Year. It needs the Date column and the other columns are optional.
```
Water Year,Date,Streamflow (mm),Sed. Del (kg),Total P (kg),Soluble Reactive P (kg),Particulate P (kg)
1990,1/1/1990,0.464,,,,
1990,1/2/1990,0.481,,,,
1990,1/3/1990,0.514,,,,
1990,1/4/1990,0.54,,,,
1990,1/5/1990,0.59,,,,
1990,1/6/1990,0.649,,,,
1990,1/7/1990,0.742,,,,
1990,1/8/1990,2.615,2621,3.24,1.16,1.363
1990,1/9/1990,1.771,1193.9,1.84,0.78,0.683
1990,1/10/1990,1.349,702.15,1.26,0.59,0.428
1990,1/11/1990,1.181,541.6,1.05,0.52,0.34
1990,1/12/1990,1.096,467.54,0.94,0.48,0.298
1990,1/13/1990,1.096,462.55,0.93,0.48,0.295
1990,1/14/1990,1.012,395.42,0.84,0.44,0.256
1990,1/15/1990,1.012,391.08,0.83,0.44,0.253
1990,1/16/1990,1.012,386.74,0.82,0.44,0.25
1990,1/17/1990,0.928,326.87,0.73,0.4,0.215
1990,1/18/1990,0.928,323.15,0.72,0.4,0.213
```

**Comment by marianadobre** [comment]
Thanks. I think it ran but it didn't display anything in the View Model Fit Results. But we can talk about it next time.

**Comment by marianadobre** [comment]
Got it this time, thanks! 

The results are still way off, though. I saw you changed the climate so now it used Tahoe station, which means that something else is the issue. I'll try to download this project and see what is the matter.
