### ISSUE TITLE
Hill slope and stream line asc/rasters download. 

### ISSUE THREAD

**Issue by ames-fowler** [rogerlew/wepppy#63]
For further processing, the inclusion of hillslope and streamline raster in project downloads would be very helpful. Please let me know if I am missing it somewhere?

**Comment by rogerlew** [comment]
My apologies, weppcloud needs better documentation. 

The hillslope and channel rasters are actually provided as .asc maps in /dem/topaz. The hillslopes are in the SUBWTA.ARC and the channels are in NETFUL.ARC.

All of the .ARC are in UTM. The interface also makes WGS geojson files for some of those to display in the interface.

Would it be helpful to have those in a different format, like geotiff?

Keep the questions coming. It be great to hear where else you are running into trouble.

**Comment by ames-fowler** [comment]
geotiff would be great, but  .asc are fine too. Thanks for the fast feedback.

**Comment by marianadobre** [comment]
Add esri shape files for subcatchments, bounds, and channels

**Comment by rogerlew** [comment]
There is now a ArcMap export for wepp runs

![image](https://user-images.githubusercontent.com/3652906/40212118-323fdf62-5a03-11e8-8208-e26faddaabd4.png)

**Comment by marianadobre** [comment]
That's great! Thank you!
