### ISSUE TITLE
13 in last line of soil files Use

### ISSUE THREAD

**Issue by rogerlew** [rogerlew/wepppy#64]
I dug through the prepwepp code and I'm pretty sure the 13 in the last line of the soils is just used by Window Wepp to set the restricting type. That allows the interface to load in predefined `uksat` based on the restricting type ( in mm/hr):
Weathered Gabbro: 0.36
Basalt: 0.0036
Unfractured Igneous and Metamorphic Rock: 0.00036

@SrivAnu
When the last line of the soil file is 1 13 10000 0.42 does WEPP actually use 13 for `aniso` and 10000 for `uksat` or does it validate those and clamp them to a range or set them to a default value?

**Comment by SrivAnu** [comment]
Roger,

The last line in the 7778 format soil should have just three values that
WEPP really cares about.

1 - flag to let WEPP know that there is a bedrock at the soil bottom.
10000 - the depth of bedrock layer (m)
0.42 - the hydraulic conductivity of bedrock (mm/hr)

13 is basically used on interfaces to allow the user to input their values.
Anisotropy values
are given for each soil layers (think its the 4th number from left).

Let me know if this clarifies or have any questions.

Anu

**Comment by SrivAnu** [comment]
Hi Roger,

Is there any WEPP interface that can uses DAYMET climate per hillslope.
Basically, I want to run a watershed to find out what could be the average
annual precipitation.

Anu

**Comment by rogerlew** [comment]
Yes, the Observed (DAYMET) option with Spatial Mode set to Multiple Climates (per hillslope) will build daymet climates per hillslope. We suspect that daymet is underestimating precip compared to prism.

**Comment by SrivAnu** [comment]
Should I use WEPP Cloud interface or Lake Tahoe? Do I need to register to
have this capability?

**Comment by rogerlew** [comment]
The climates should be the same for the regular WEPP Cloud interface and LakeTahoe. No need to register.

**Comment by rogerlew** [comment]
P.S. Thanks for the confirmation regarding the soil file

**Comment by SrivAnu** [comment]
Your welcome.

Here's the error I am getting for climate on WEPP Cloud.

Error building climate

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wepppy/weppcloud/app.py", line
1526, in task_build_climate
    climate.build()
  File "/usr/lib/python3/dist-packages/wepppy/nodb/climate.py", line
631, in build
    self._build_climate_observed()
  File "/usr/lib/python3/dist-packages/wepppy/nodb/climate.py", line
751, in _build_climate_observed
    lng=lng, lat=lat
  File "/usr/lib/python3/dist-packages/wepppy/climates/cligen_client.py",
line 172, in observed_daymet
    assert isint(par)
AssertionError

Also, for some reason, landuse is always selected bare for "single
landuse option.

**Comment by SrivAnu** [comment]
But the message underneath the climate build tab says that its building
climate. Probably, I should wait.

**Comment by rogerlew** [comment]
I think you have to select a climate station and then click the Build button

**Comment by SrivAnu** [comment]
Got it. Thank you.
