### ISSUE TITLE
Error running wepp

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#68]
I ran this one with PRISM and crashed. I know PRISM it's running fine because I ran it earlier on the general interface. I'm not sure why the error appeared on Tahoe.  

Error running wepp

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wepppy/weppcloud/app.py", line 1814, in submit_task_run_wepp
    wepp.run_watershed()
  File "/usr/lib/python3/dist-packages/wepppy/nodb/wepp.py", line 763, in run_watershed
    wepppost.run_post()
  File "/usr/lib/python3/dist-packages/wepppy/nodb/wepppost.py", line 157, in run_post
    assert len(_julians) == len(_days)
AssertionError

**Comment by rogerlew** [comment]
I can take a look at it. Which run is it?

**Comment by marianadobre** [comment]
I think it's this one:

https://wepp1.nkn.uidaho.edu/weppcloud/runs/cdcd9619-2cb8-48be-94dd-3c88908be406/lt/

**Comment by rogerlew** [comment]
It looks like the ebe_pw0.txt didn't have any data. I'm not sure why. I reran it and got the same result. I also tried rebuilding the climates and had the same result. Might be a question for Anu...

I at least have it check to provide a more informative error message.

**Comment by rogerlew** [comment]
I'm closing this since it looks like it is related to WEPP.
