### ISSUE TITLE
combined watershed maps

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#70]
Develop code to produce output maps of multiple watersheds,
runoff, soil loss, phosphorus, etc.

Need to be able to identify the watershed and hillslope from the map.

**Comment by rogerlew** [comment]
p.s. I haven't tested it with Internet Explorer

**Comment by marianadobre** [comment]
Wow! This works great and I think this will be very useful for people. So next would be to click on a hillslope and have another window displaying hillslope values, watershed name/number, and a link to that watershed run? I really think this is developing into a very nice tool! I’ll try it on IE when I get to the office. 

Mariana

**Comment by rogerlew** [comment]
Cool, there should actually be a popup if you click on a hillslope. I could get it to work on my phone. But it should work on a computer.?

**Comment by rogerlew** [comment]
Hopefully, they should be able to use Edge. Microsoft is phasing out Internet Explorer. I'm going to close this. Feel free to create new issues for bugs/additional features.
