### ISSUE TITLE
Truncate the legend for dNBR maps

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#79]
When we upload a dNBR map we get a list of all 256 values, which clogs the page and makes it hard to handle. Can we, after we set the breaks, display the dNBR in a simplified manner? Otherwise users will have to scroll all the way to the bottom of the page to build the subcatchments.  This works better with SBS maps because those are just 4 classes.

**Comment by rogerlew** [comment]
Awe, I see how that could be problematic. I made it a collapsible table. It should be hidden by default.
