### ISSUE TITLE
Chanwb doesn't have data

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#85]
I think I remember seeing this before but can't remember why it didn't print anything. Do you?

https://wepp1.nkn.uidaho.edu/weppcloud/runs/a4ec47da-c751-49c5-8cba-3eb8a0e2eac0/baer/

**Comment by rogerlew** [comment]
That does seem familiar, but it could be new. I think the other outputs we were having problems with were ebe_pw0.txt and chntyp.txt.

@SrivAnu have you seen WEPP produce an empty chanwb.out before? or any idea why?
https://wepp1.nkn.uidaho.edu/weppcloud/runs/a4ec47da-c751-49c5-8cba-3eb8a0e2eac0/browse/wepp/output/chanwb.out

**Comment by SrivAnu** [comment]
Does this happen if you delineate small watersheds?

**Comment by SrivAnu** [comment]
The one that I ran just now did not have this problem.

**Comment by SrivAnu** [comment]
The one that you are looking at, it seems that the contents of chanwb.out
are printed out in this file

https://wepp1.nkn.uidaho.edu/weppcloud/runs/a4ec47da-c751-49c5-8cba-3eb8a0e2eac0/browse/wepp/runs/chntyp.txt/

**Comment by SrivAnu** [comment]
I will need to fix a couple of things in WEPP codes to fix this issue.
