### ISSUE TITLE
Error deliniating watershed

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#86]
Here's an error, not sure why it could not delineate the channels.
https://wepp1.nkn.uidaho.edu/weppcloud/runs/848532f4-0b6b-403c-b013-4356bd05c0cc/0/

**Comment by marianadobre** [comment]
Also this one, the same error:
https://wepp1.nkn.uidaho.edu/weppcloud/runs/5cc6eb63-ad70-412b-9939-cceb5478b6f9/0/

**Comment by rogerlew** [comment]
Looks like there are some elevation values smaller than 1.0 in the DEM.

I think that should be a quick fix to clamp those to 1.0. I'll see if I can fix it now.


From DEDNM.RPT
```
 ***** BEGINNING DEM INPUT AND DEM PRE-PROCESSING.
 === ALLOCATING IEL ARRAY.
 *** BEGINNING SBRT INDEM.
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 !!!!!!!!!!!!!!  ERROR  !!!!!!!!!!!!!!
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 SUBROUTINE INDEM; MODULE DEDNM2 (M_DEDNM2.F90).
 INPUT FILE DEDNM.INP.
 THE INPUT DEM ELEVATION VALUES MUST BE GREATER THAN 1.0,
 AND SMALLER THAN 9999.0 METERS.
 THE VALUE READ WAS :    0.9 .
 ERROR AT ROW =     1; COLUMN =    98 .
```

**Comment by marianadobre** [comment]
I see. When we delineate watersheds in ArcGIS we are filling in the DEM, I
guess because of this exact reason. I don't know if there is a command in
python to fill in all the DEM's before taking them to TOPAZ.

Thanks for looking at this!

**Comment by rogerlew** [comment]
Looks like it is working now.

There is a Python routine in wepppy that builds the DEDNM.INP file for topaz. It is an ascii with the elevation values as a single column. I just used np.clip to make sure they are between 1 and 9999. As that all that the 

ArcGIS filling does?

**Comment by marianadobre** [comment]
I think the filling is just like you said, making all the values 1. 

Thank you!
