### ISSUE TITLE
Flowpath output 

### ISSUE THREAD

**Issue by ames-fowler** [rogerlew/wepppy#93]
Three questions 

- How are the flow path output data housed in the downloaded project? Is there a synthesized raster as plotted online that I am not finding. 
- Is there water balance data associated with each flow path? 
- Is the hillslope boundary and flowpath boundary different, or using DEMs with different alignments (see attached photo).

Thanks
![image](https://user-images.githubusercontent.com/31111462/45441492-0029c880-b674-11e8-826b-a20005781886.png)

**Comment by rogerlew** [comment]
Hi Ames,

The flowpath output is hidden in wepp/plots/loss.WGS.tif

Right now it is only creating loss and plot files for the flowpaths, but I have it generate the water balance output files if you would want that.

It should be noted that the loss at each cell is calculated as the average of the flowpath loss at each cell. I don't believe there has ever been validation for that. That was how Jim was doing it with the old interface. He also experimented with taking a weighted average based on the distance from the pourpoint for each flowpath. 

The alignment might need some investigation. It could be a projection issue. I think there should be a UTM map in the wepp/plots folder as well. Let me know if you figure anything out there.

**Comment by ames-fowler** [comment]
Thank you Rodger,

I am interested in flow path water balance outputs, but it is not at all time sensitive right now.

I will look into the UTM map and loss.WGS.tif.

Cheers,

Ames

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by rogerlew** [comment]
I changed the run file template for the flowpaths so you should get the water balance outputs. You should be able to just rerun wepp. Let me know what if it doesn’t work. I didn’t test it.
