### ISSUE TITLE
error

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#94]
Just got this error. Any idea why?

https://wepp1.nkn.uidaho.edu/weppcloud/runs/mdobe1cb-020e-4c87-995d-584be49c67a6/lt/

Error running wepp

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wepppy/weppcloud/app.py", line 1879, in submit_task_run_wepp
    wepp.run_hillslopes()
  File "/usr/lib/python3/dist-packages/wepppy/nodb/wepp.py", line 527, in run_hillslopes
    plo = PlotFile(_join(self.fp_output_dir, '%s.plot.dat' % fp))
  File "/usr/lib/python3/dist-packages/wepppy/wepp/out/plot.py", line 24, in __init__
    data = data.reshape((100, 3)).T
ValueError: cannot reshape array of size 0 into shape (100,3)

**Comment by ames-fowler** [comment]
I have gotten this error too but got caught up in things. I think I started occurring while running flow paths after I requested flow path water balance components. Is this true or a coincidence?




________________________________

**Comment by marianadobre** [comment]
Funny, I just opened an issue on github with the same error three hours
ago.

It might just be a recent bug. Will have to wait on Roger to look at it.

Mariana

**Comment by rogerlew** [comment]
@ames-fowler thanks for jogging my memory.

The flowpath run files weren't specifying the name of the flowpath waterbalance output file. I think this is why it is crashing.

Testing it now...

**Comment by rogerlew** [comment]
yep, looks like that it.
@marianadobre, I cloned your lt project to here and ran it.
https://wepp1.nkn.uidaho.edu/weppcloud/runs/100c5603-9f6f-4ed6-8e00-034854b8e3f7/lt/
