### ISSUE TITLE
New report

### ISSUE THREAD

**Issue by marianadobre** [rogerlew/wepppy#95]
Name: Particle site distribution

From totalwatsed.txt (% Class 1, 2, and 5)--for hillslope erosion.
From loss_pw0.txt (% clay, silt, sand) these are in fractions, change to %--for outlet.

**Comment by rogerlew** [comment]
Would you mind uploading your totalwatsed spreadsheet so I can see how to aggregate the class values? 

I figured out how the particle distributions are being calculated based on the Sediment Particle Information Leaving Channel Table. I can use the same class compositions so we get an apples to apples comparison between the totalwatsed and loss_pw0.

![image](https://user-images.githubusercontent.com/3652906/48154077-9d703a00-e27c-11e8-95c3-ef1742dd5761.png)

**Comment by rogerlew** [comment]
This is in the sediment delivery report
